const posts = [
  {
    srcProfile: "assets/images/story/loud-story.jpg",
    name: "loud",
    srcImg: "assets/images/loud-champions.jpg",
    srcLike: "assets/images/story/sacy.jpg",
    nameLike: "sacy",
    likeNumber: "995",
    nameComment: "brad_breach",
    comment: "Melhores do mundo",
    nameCommentTwo: "yaki_sova",
    commentTwo: "Faz o L!!!",
    commentNumber: "322",
  },
  {
    srcProfile: "assets/images/aside/f1.png",
    name: "formula1",
    srcImg: "",
    srcVideoMp4: "assets/videos/DonutsF1.mp4",
    srcVideoOgg: "assets/videos/DonutsF1.ogx",
    srcLike: "assets/images/leclerc.jpg",
    nameLike: "charles_leclerc",
    likeNumber: "947",
    nameComment: "p.b.teron",
    comment: "Apenas beleza",
    nameCommentTwo: "falkol",
    commentTwo: "Incrível",
    commentNumber: "234",
  },
  {
    srcProfile: "assets/images/meowed 2.svg",
    name: "meowed",
    srcImg: "assets/images/gato-telefone 1.svg",
    srcLike: "assets/images/story/muzy.jpeg",
    nameLike: "muzy",
    likeNumber: "823",
    nameComment: "butterfly",
    comment: "Aww tão fofo",
    nameCommentTwo: "jojo",
    commentTwo: "Ótima foto",
    commentNumber: "140",
  },
  {
    srcProfile: "assets/images/barked 2.svg",
    name: "barked",
    srcImg: "",
    srcVideoMp4: "assets/videos/video.mp4",
    srcVideoOgg: "assets/videos/video.ogx",
    srcLike: "assets/images/adorableanimals 2.svg",
    nameLike: "adorable_animals",
    likeNumber: "213",
    nameComment: "mango12",
    comment: "Que adorável",
    nameCommentTwo: "callie",
    commentTwo: "kkkk muito bom",
    commentNumber: "85",
  },
];

export default posts;
