const posts = [
  {
    srcProfile: "assets/images/story/loud-story.jpg",
    name: "loud",
    srcPost: "assets/images/loud-champions.jpg",
    srcLike: "assets/images/story/sacy.jpg",
    nameLike: "sacy",
    likeNumber: "995",
    nameComment: "brad_breach",
    comment: "Melhores do mundo",
    nameCommentTwo: "yaki_sova",
    commentTwo: "Faz o L!!!",
    commentNumber: "322",
  },
  {
    srcProfile: "assets/images/barked 2.svg",
    name: "barked",
    srcPost: "assets/images/BlackBear.jpg",
    srcLike: "assets/images/adorableanimals 2.svg",
    nameLike: "adorable_animals",
    likeNumber: "454",
    nameComment: "p.b.teron",
    comment: "Apenas beleza",
    nameCommentTwo: "falkol",
    commentTwo: "Incrível",
    commentNumber: "125",
  },
  {
    srcProfile: "assets/images/meowed 2.svg",
    name: "meowed",
    srcPost: "assets/images/gato-telefone 1.svg",
    srcLike: "assets/images/story/muzy.jpeg",
    nameLike: "muzy",
    likeNumber: "823",
    nameComment: "butterfly",
    comment: "Aww tão fofo",
    nameCommentTwo: "jojo",
    commentTwo: "Ótima foto",
    commentNumber: "140",
  },
];

export default posts